### ISSUE TITLE
simple login page 

### ISSUE THREAD

**Issue by zorostang** [zorostang/nft-authorization-front-end#1]
**Acceptance Criteria:**
As a user who has downloaded the keplr wallet, I should be able to authorize my credentials simply by connecting my wallet to a web2 page.

**Implementation ideas:**
NFT id numbers as user names

**Future Use Cases:**
- Transfer of ownership
  - Selling a high level game character 
  - Transferring bank assets

**Comment by kent-3** [comment]
Can I work on this project? The emoji suggests it is already assigned, but there is no code or assignees here.

**Comment by zorostang** [comment]
Hi @kent-3 Thanks for reaching out. @Xiphiar will reach out to you about this if he hasn't already.

**Comment by luminaryphi** [comment]
Hello. I don't think it was mentioned here, but the smart contract side is using a pair of [u8; 32] as a keypair which would be verified by this.
